-- 0004_seed_factors: 13 factors (5 core ALL, 4 clinical C, 4 non-clinical N), 5-level anchors
-- Anchors pending HR sign-off (form proposal open item 3); edits via /admin/settings affect future cycles only.
INSERT INTO factor (code, track, sort, label, description, anchors) VALUES
('B1','ALL',1,'Reliability (punctuality & attendance)','Punctuality, attendance discipline and leave behaviour. Late-count and leave-days are entered as data alongside the score.',
'{"5":"No unexplained lates or absences in the period; leave always within entitlement and with prior intimation; can be depended on for duty continuity.",
  "4":"Punctual and regular with only rare, well-explained exceptions; leave within entitlement, almost always with prior intimation.",
  "3":"Generally within entitlement and broadly punctual; occasional lapses that are explained satisfactorily.",
  "2":"Repeated lateness or unplanned absence; leave at times without prior intimation or exceeding entitlement.",
  "1":"Habitual lateness or absenteeism; attendance unpredictable; disrupts duty rosters."}'::jsonb),
('B2','ALL',2,'Ownership & commitment','Involvement with work, responsibility for outcomes, follow-up needed.',
'{"5":"Drives work to completion unprompted; takes responsibility for outcomes beyond own tasks; others rely on them in a crunch.",
  "4":"Strives hard and can be relied upon to give their best; needs no follow-up on assigned work.",
  "3":"Completes assigned tasks as instructed with minimal follow-up; involvement adequate for the role.",
  "2":"Involvement barely adequate; does not go out of the way to complete tasks; needs frequent follow-up.",
  "1":"No sense of involvement or responsibility; needs constant follow-up and close supervision."}'::jsonb),
('B3','ALL',3,'Communication','Clarity and effectiveness of oral and written communication with patients, colleagues and seniors; escalation behaviour.',
'{"5":"Precise and effective with every audience; adapts language for patients vs clinicians; escalates the right things at the right time.",
  "4":"Consistently clear oral and written communication; rarely misunderstood; documents and hands over well.",
  "3":"Clear and satisfactory communication for routine work.",
  "2":"Communication barely adequate; causes occasional confusion or rework; needs improvement.",
  "1":"Communication grossly inadequate; causes errors, missed handoffs or friction."}'::jsonb),
('B4','ALL',4,'Teamwork & respect','Working relationships with colleagues, superiors, patients and visitors; conflict behaviour.',
'{"5":"Builds smooth relationships across departments; de-escalates conflict; patients and colleagues specifically seek them out.",
  "4":"Gets along very well with colleagues, superiors and patients; takes pains to keep relationships sound.",
  "3":"Co-operative; generally gets along well; only rare incidents of friction.",
  "2":"Noticeable incidents of strained relationships; co-operation inconsistent.",
  "1":"Frequent strained relationships with colleagues, superiors or patients."}'::jsonb),
('B5','ALL',5,'Adaptability & openness','Receptiveness to new ideas, methods, feedback and change.',
'{"5":"Volunteers to try new methods; brings constructive suggestions; helps others adapt to change.",
  "4":"Receptive to new ideas and suggestions; tries new approaches whenever required.",
  "3":"Accepts change when asked; not averse to new ideas.",
  "2":"Shows resistance to change; indifferent to suggestions and feedback.",
  "1":"High resistance to change; rejects feedback; blocks improvement."}'::jsonb),
('C1','C',6,'Clinical knowledge & skill','Knowledge and skill for the clinical role; growth of competence.',
'{"5":"Mastery beyond role requirements; acts as a resource person and teaches others; rarely needs clarification.",
  "4":"Well acquainted with all aspects of own clinical duties; seeks clarification only when genuinely required.",
  "3":"Sound knowledge of routine duties; seeks guidance appropriately for non-routine work.",
  "2":"Knowledge barely adequate for routine work; requires regular guidance.",
  "1":"Gaps in basic knowledge or skill that put safe practice at risk; needs constant supervision."}'::jsonb),
('C2','C',7,'Patient safety & protocol adherence','Adherence to safety protocols: patient identification, medication safety, infection control, handoffs; near-miss reporting.',
'{"5":"Exemplary adherence; actively reports near-misses and prompts others; zero shortcuts observed.",
  "4":"Reliable adherence to all protocols; occasionally reminds peers; no safety incidents attributable.",
  "3":"Follows protocols; needs occasional reminders; no significant lapses.",
  "2":"Lapses in adherence requiring correction; needs active supervision on safety practice.",
  "1":"Shortcuts or violations that create real risk to patients."}'::jsonb),
('C3','C',8,'Quality of care & documentation','Quality and consistency of care delivered; accuracy, timeliness and completeness of clinical records.',
'{"5":"Consistently high quality care; records accurate, timely and complete; sets the example others follow.",
  "4":"Maintains high quality output; documentation reliably complete with rare corrections.",
  "3":"Acceptable care quality and documentation; needs occasional guidance for consistency.",
  "2":"Inconsistent quality; documentation needs frequent correction or chasing.",
  "1":"Careless care or documentation; does not meet standard requirements."}'::jsonb),
('C4','C',9,'Patient experience & empathy','Courtesy, compassion and communication with patients and attendants.',
'{"5":"Patients and attendants specifically commend them; communicates difficult information with compassion.",
  "4":"Warm, attentive and professional with patients consistently.",
  "3":"Courteous and professional in patient interactions.",
  "2":"Occasional complaints or brusque behaviour; needs coaching.",
  "1":"Repeated complaints about behaviour towards patients or attendants."}'::jsonb),
('N1','N',6,'Job knowledge & process mastery','Knowledge of own processes, systems and adjacent functions.',
'{"5":"Expert in own processes and conversant with adjacent ones; the person others ask; rarely needs clarification.",
  "4":"Well acquainted with all aspects of own work methods and procedures.",
  "3":"Knows own processes well enough for routine work; seeks guidance for exceptions.",
  "2":"Process knowledge barely adequate; requires regular guidance.",
  "1":"Lacks basic process knowledge; needs constant supervision."}'::jsonb),
('N2','N',7,'Work output & timeliness','Productivity against targets and turnaround times.',
'{"5":"Consistently ahead of TAT and targets; productivity visibly higher than peers in similar work.",
  "4":"Frequently exceeds targets; dependable under load.",
  "3":"Meets TAT and targets; achieves them with normal follow-up.",
  "2":"Output requires chasing; misses deadlines at times.",
  "1":"Drags on with work; frequently falls short of targets."}'::jsonb),
('N3','N',8,'Quality & accuracy','Error rates, rework, dependability of output.',
'{"5":"Near-zero rework; others rely on their output without checking.",
  "4":"High quality output; errors rare and self-caught.",
  "3":"Acceptable accuracy; occasional corrections needed.",
  "2":"Inconsistent quality; needs instructions and review to maintain standards.",
  "1":"Frequent errors and rework; perceptible lack of quality consciousness."}'::jsonb),
('N4','N',9,'Service orientation & improvement','Responsiveness to internal customers and patients; initiative on process improvement.',
'{"5":"Anticipates needs of patients and internal customers; proposes and lands process improvements.",
  "4":"Highly responsive; occasionally suggests improvements that get adopted.",
  "3":"Responds well to requests; service adequate and courteous.",
  "2":"Slow or indifferent responses at times; no improvement initiative.",
  "1":"Indifferent to service quality; source of internal complaints."}'::jsonb)
ON CONFLICT (code) DO NOTHING;
