-- 0005_seed_ehrc_roster: 74 EHRC employees + appraisers from 'Appraisals & HODs List.xlsx' (normalised)
-- See content/ROSTER-CLEANUP-REPORT.md for normalisation decisions. PENDING-HR: name-variant dedupe (kept verbatim).

INSERT INTO appraiser (full_name) VALUES
  ('Chandrika Kambam'),
  ('Binita Priyambada'),
  ('Yash Sharma / Dr Vinay'),
  ('Anand S'),
  ('Chandrakala LN'),
  ('Shubha Mangala'),
  ('Rajesh'),
  ('C vinod Kumar'),
  ('Ravi Sekhar N'),
  ('Bhavesh Nainani'),
  ('Lavanya'),
  ('C S Yogendra'),
  ('Mitsha Signh'),
  ('Akhila R'),
  ('M Balakrishna'),
  ('Manjunath'),
  ('Dr Chandrika'),
  ('Dr Prashant'),
  ('Dr Gautham'),
  ('Dr Ankita Priya')
ON CONFLICT DO NOTHING;

INSERT INTO employee (hospital_id, emp_code, full_name, department, sub_department, designation, track, default_appraiser_id) VALUES
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA026', 'Shubha Mangala H T', 'Hospital Administration', 'Nursing', 'Head of Nursing', 'C', (SELECT id FROM appraiser WHERE full_name='Chandrika Kambam' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA027', 'Anushree S', 'Clinical Internal', 'Dietetics', 'Dietician', 'C', (SELECT id FROM appraiser WHERE full_name='Binita Priyambada' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA028', 'B Ajith Kumar', 'Hospital Administration', 'Pharmacy', 'Senior Pharmist', 'C', (SELECT id FROM appraiser WHERE full_name='Yash Sharma / Dr Vinay' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA031', 'K Ravikumar', 'Hospital Administration', 'Sales & Marketing', 'Manager - Sales & Marketing', 'N', (SELECT id FROM appraiser WHERE full_name='Anand S' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA035', 'Venkatesh Babu S', 'Clinical Hospital', 'Laboratory', 'Lab Technician', 'C', (SELECT id FROM appraiser WHERE full_name='Chandrakala LN' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA038', 'Mary Nirmala S', 'Clinical Hospital', 'Nursing', 'ICU/Ward Incharge', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA040', 'Anoop M A', 'Clinical Hospital', 'Radiology', 'Radiographer', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA044', 'Hanchanahal Harsha Vardhan Gowd', 'Hospital Administration', 'Pharmacy', 'Pharmacist', 'C', (SELECT id FROM appraiser WHERE full_name='Rajesh' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA047', 'Ankitha', 'Clinical Hospital', 'OT/Anes Technician', 'OT Technician', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA048', 'K Anuja', 'Clinical Hospital', 'Nursing', 'NICU Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA053', 'Suby Varghese', 'Clinical Hospital', 'Nursing', 'Ward Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA054', 'Jamuna M', 'Hospital Administration', 'Billing', 'Executive ( Billing / front desk )', 'N', (SELECT id FROM appraiser WHERE full_name='C vinod Kumar' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA055', 'Umesha', 'Clinical Hospital', 'Dialysis Technician', 'Dialysis Technician', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA056', 'Sathyamoorthy', 'Hospital Administration', 'Finance', 'Senior Manager - Finance & Accounts', 'N', (SELECT id FROM appraiser WHERE full_name='Ravi Sekhar N' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA059', 'Geethamma N', 'Clinical Hospital', 'Nursing', 'Staff Nurse ER/ICU', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA061', 'Khatija Khanum', 'Clinical Hospital', 'Pharmacy', 'Clinical Pharmacologist', 'C', (SELECT id FROM appraiser WHERE full_name='Yash Sharma / Dr Vinay' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA062', 'C S Yogendra', 'Hospital Administration', 'Supply Chain Management', 'Manager - Supply Chain Management', 'N', (SELECT id FROM appraiser WHERE full_name='Yash Sharma / Dr Vinay' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA063', 'Rajeshwari M', 'Clinical Hospital', 'Nursing', 'Senior OBG/GYN Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA064', 'Anand S', 'Hospital Administration', 'Sales & Marketing', 'General Manager - Sales and Marketing', 'N', (SELECT id FROM appraiser WHERE full_name='Bhavesh Nainani' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA065', 'Lisu Rose Mathew', 'Clinical Hospital', 'Nursing', 'Ward Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA066', 'Vishnu Kumar S', 'Clinical Hospital', 'Radiology', 'Radiographer', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA068', 'Md Shoaib Ahmed', 'Clinical Hospital', 'Laboratory', 'Lab Technician', 'C', (SELECT id FROM appraiser WHERE full_name='Chandrakala LN' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA069', 'Ramya G', 'Clinical Hospital', 'Echo Technician', 'Echo Technician', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA070', 'Rohit Syngkli', 'Clinical Hospital', 'Nursing', 'OT Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA072', 'Sekh Kiron Rahaman', 'Clinical Hospital', 'Endoscopy', 'Endoscopy Technician', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA073', 'Chandrakala L N', 'Clinical Hospital', 'Laboratory', 'Team Leader - Laboratory', 'C', (SELECT id FROM appraiser WHERE full_name='Yash Sharma / Dr Vinay' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA077', 'Madhivannan M', 'Hospital Administration', 'Customer Care', 'Associate Front Office', 'N', (SELECT id FROM appraiser WHERE full_name='Lavanya' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA084', 'G Nivedita', 'Clinical Hospital', 'Pathology', 'Pathologist', 'C', (SELECT id FROM appraiser WHERE full_name='Chandrika Kambam' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA085', 'Panora Matlang', 'Clinical Hospital', 'Nursing', 'LDR Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA086', 'Devaraj', 'Clinical Hospital', 'Nursing', 'ER Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA087', 'Shruthi K', 'Clinical Hospital', 'Nursing', 'Senior Associate', 'C', (SELECT id FROM appraiser WHERE full_name='Lavanya' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA088', 'Suchithra K M', 'Clinical Hospital', 'Nursing', 'ICU Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA089', 'Shakthi Raja', 'Clinical Hospital', 'Nursing', 'OT Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA090', 'Kamar Afshan M', 'Clinical Hospital', 'Dietetics', 'Manager CND', 'C', (SELECT id FROM appraiser WHERE full_name='Chandrika Kambam' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA075', 'C vinod Kumar', 'Clinical Hospital', 'Hospital Administration', 'Billing Manager', 'N', (SELECT id FROM appraiser WHERE full_name='Yash Sharma / Dr Vinay' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA076', 'Umagowri M', 'Clinical Hospital', 'Finance', 'Assistnat Manager - Accountants & Payables', 'N', (SELECT id FROM appraiser WHERE full_name='Ravi Sekhar N' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA092', 'Archana K S', 'Clinical Hospital', 'Radiology', 'Radiographer', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA094', 'Tamanna Banu', 'Clinical Hospital', 'Customer Care', 'Senior Executive Front Office', 'N', (SELECT id FROM appraiser WHERE full_name='C vinod Kumar' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA095', 'Aishwarya M', 'Clinical Hospital', 'Customer Care', 'Front Office Executive', 'N', (SELECT id FROM appraiser WHERE full_name='Lavanya' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA096', 'Deepu S', 'Clinical Hospital', 'Admin', 'Management trainee', 'N', (SELECT id FROM appraiser WHERE full_name='Yash Sharma / Dr Vinay' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA097', 'Vanitha K', 'Clinical Hospital', 'Supply Chain Management', 'Executive GRN', 'N', (SELECT id FROM appraiser WHERE full_name='C S Yogendra' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA099', 'VIJAY IRAPPA BYAKUD', 'Clinical Hospital', 'Pharmacy', 'Pharmacist', 'C', (SELECT id FROM appraiser WHERE full_name='Rajesh' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA100', 'Charan Kumar S', 'Clinical Hospital', 'Admin', 'Facility Manager', 'N', (SELECT id FROM appraiser WHERE full_name='Yash Sharma / Dr Vinay' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA101', 'Amitava Mondal', 'Clinical Hospital', 'Nursing', 'Ward Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA103', 'Lavanya R', 'Clinical Hospital', 'Customer Care', 'Front Desk TL', 'N', (SELECT id FROM appraiser WHERE full_name='C vinod Kumar' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA105', 'Muniraja N N', 'Clinical Hospital', 'Nursing', 'ICU/ER Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA107', 'ASHRITHA B', 'Clinical Hospital', 'Laboratory', 'Lab Technician', 'C', (SELECT id FROM appraiser WHERE full_name='Chandrakala LN' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA108', 'Manjunath Y', 'Hospital Administration', 'Human Resources', 'Manager - HRBP', 'N', (SELECT id FROM appraiser WHERE full_name='Mitsha Signh' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA110', 'Sudheer Kumar R', 'Hospital Administration', 'Admin', 'MOD', 'N', (SELECT id FROM appraiser WHERE full_name='Yash Sharma / Dr Vinay' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA112', 'Vidhya Lakshmi', 'Hospital Administration', 'Human Resources', 'HR - Executive', 'N', (SELECT id FROM appraiser WHERE full_name='Akhila R' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA113', 'Akhil Mohanan', 'Clinical Hospital', 'OT/Anes Technician', 'OT Technician & OT Store Incharge', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA114', 'Pradeep Malipatil', 'Clinical Hospital', 'Pharmacy', 'Pharmacist', 'C', (SELECT id FROM appraiser WHERE full_name='Rajesh' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA115', 'Nagesh', 'Hospital Administration', 'Sales & Marketing', 'Business Development Manager (surgery)', 'N', (SELECT id FROM appraiser WHERE full_name='M Balakrishna' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA116', 'ARNAB PAUL', 'Hospital Administration', 'Sales & Marketing', 'Business Development Manager (surgery)', 'N', (SELECT id FROM appraiser WHERE full_name='M Balakrishna' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA117', 'Saranya Sasikumar', 'Clinical Hospital', 'OT/Anes Technician', 'Anesthesia & OT Technician', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA118', 'Ankita Priya', 'Hospital Administration', 'Admin', 'Assitant Manager - medical Admin', 'N', (SELECT id FROM appraiser WHERE full_name='Chandrika Kambam' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA119', 'A Latha', 'Clinical Hospital', 'Nursing', 'Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA120', 'Rahul Rajeshwarrao Parsatwar', 'Hospital Administration', 'Sales & Marketing', 'Business Development Manager (surgery)', 'N', (SELECT id FROM appraiser WHERE full_name='M Balakrishna' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA121', 'Naveen B', 'Hospital Administration', 'Admin', 'HR L & D', 'N', (SELECT id FROM appraiser WHERE full_name='Manjunath' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA122', 'Madhu Sudhan', 'Hospital Administration', 'Supply Chain Management', 'Senior Executive - Stores', 'N', (SELECT id FROM appraiser WHERE full_name='C S Yogendra' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA124', 'Raju', 'Clinical Hospital', 'Nursing', 'ER Staff Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA126', 'M D Ather Nesar', 'Hospital Administration', 'Sales & Marketing', 'Business Development Manager (surgery)', 'N', (SELECT id FROM appraiser WHERE full_name='M Balakrishna' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA128', 'Cema I', 'Hospital Administration', 'Sales & Marketing', 'Business Development Manager (surgery)', 'N', (SELECT id FROM appraiser WHERE full_name='M Balakrishna' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA129', 'Shylaja C', 'Hospital Administration', 'Finance', 'Executive - Finance & Accounts', 'N', (SELECT id FROM appraiser WHERE full_name='Ravi Sekhar N' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA131', 'C Kamalam', 'Clinical Hospital', 'Nursing', 'Senior OT Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA132', 'Satyam Kumar', 'Clinical Hospital', 'Nursing', 'OT Nurse', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA133', 'Sibin Saji', 'Clinical Hospital', 'Radiology', 'Radiographer', 'C', (SELECT id FROM appraiser WHERE full_name='Shubha Mangala' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA100061', 'Shilpa Rajendran', 'Clinical Hospital', 'Intensive Care', 'Consultant Intensivist', 'C', (SELECT id FROM appraiser WHERE full_name='Dr Chandrika' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA100064', 'Karthik K S', 'Clinical Hospital', 'Orthopedics', 'Registrar Orthopedics', 'C', (SELECT id FROM appraiser WHERE full_name='Dr Prashant' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA100066', 'R Ayyappa', 'Clinical Hospital', 'Emergency Service', 'ER Physician - RMO', 'C', (SELECT id FROM appraiser WHERE full_name='Dr Gautham' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA100074', 'Fasahath Faraz Khan', 'Clinical Hospital', 'Intensive Care', 'ICU Physician', 'C', (SELECT id FROM appraiser WHERE full_name='Dr Ankita Priya' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA100076', 'Nishita Das', 'Clinical Hospital', 'Pediatrics', 'Associate Consultant - Pediatrician', 'C', (SELECT id FROM appraiser WHERE full_name='Dr Chandrika' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA100091', 'Ankit P Bhojani', 'Clinical Hospital', 'Internal Medicine', 'Consultant physician', 'C', (SELECT id FROM appraiser WHERE full_name='Dr Chandrika' LIMIT 1)),
  ((SELECT id FROM hospital WHERE code='EHRC'), 'BA100092', 'PRAJETH S S', 'Clinical Hospital', 'ICU', 'ICU Physician - RMO', 'C', (SELECT id FROM appraiser WHERE full_name='Dr Ankita Priya' LIMIT 1))
ON CONFLICT (hospital_id, emp_code) DO NOTHING;
